osx_image: xcode10.1
dist: trusty
sudo: required
language: node_js
node_js: 8.12.0
addons:
  chrome: stable
os: windows
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

script:
  - npm run dist

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FouILvfCHG+swHd7JmtH+yamYI4D5F066CsJrgGCPFEP6SlpDYEebL/3ZqTScjKIB9SDZPAwlCDNCw0XtB5SspndPG9ccTVYPnj3CccqGKoTzOZgiRrKudVucar36pxK61u1Cbq80T9CpHAdlidTN6ZWUjNI1fgpCOwPY6ARCjR38702ZFuaQqaJJ89R1lB+H3ICzB47NkCCoSSzsrz4TdBY22yfxZn4AcyJfEarMvms313C45LRj44X9G5QtaaDKHRb+mTzYzpmMTinz05PsA81ymqNAxbfRuFFy9A08ElwoC0gdE0wSS7KBjpi+vtfkCfmBDjE02dtHtMhlrC2KSsj1WAd9kwwmJkoCoyduOx0ezYkVXcewrUuyffnGgTbEM8oAoxDtCgI3GygQcrXWuJK74+AhBJU5NPdEygO5kZXcz5hkDX88b4hySVUnkY9Pfx5IaNEMymdRBzd0MiswaNt2EFdngwnJJegz8GAgOrQVKN3gc0C1bNyjhjK7SCckNkxKlKUjOb8hXY0PMQYtLfBdRYhhliuBmT5USG+TCn5XFOWXiAjuufH455Yz5kXkKKQVY+VmBsdJMHV3nTDUyw3jcp5QTd2FZkBOlzn25XHX2oWiFFvYwqA3aPM90cN1HeFsr4KVakKLAnb900cBPhiNKGxNuGiK0ajMmBnQ0A=
  file: "dist/passwordscreator Setup 0.0.1.exe"
  name: PasswordCreator $(date +'%d.%m.%Y %R')
  on:
    repo: reach2jeyan/PasswordsCreator
    branch: autodeploy

